import time
import random
hitonoticia = False
#FUNCIONES BASE
def webcam():
    print("Así que quieres una foto, ¿eh?")
    #time.sleep(1)
    print("Qué coquette es miniña.")
    #time.sleep(1)
    print("Ponte guapa, amore.")
    #time.sleep(0.5)
    print("Más de lo normal, quiero decir.")
    #time.sleep(1)
    print("¡Di patata!")
    #time.sleep(0.5)
    print("¿O eso ya no se dice?")
    #time.sleep(0.5)
    print("Da igual.")
    #time.sleep(0.5)
    print("¡Que voy!")
    foto = random.randint(1,6)
    if foto == 1:
        descarga = "https://mega.nz/file/JjcQEKCD#wFpXg5nmk6qJ4IB1UwQxE5OgkcMba_lozHILuVHHVdc"
        opinion = "Tía, mira que te gusta hacer el tonto, tómatelo en serio."
    elif foto == 2:
        descarga = "https://mega.nz/file/hj0ACBpD#ltJoTtt20mMI9pQVLl1NNAfT3_zSoSJHOuixOc74alY"
        opinion = "Ay, demasiado sobria, nena. Guapísima, pero sobria. Date algo más de vidilla, toda la que tienes, que no te falta de eso."
    elif foto == 3:
        descarga = "https://mega.nz/file/Vq8iETaa#nKpQwZnJjCqwhmPOK_xVfPijUo7Ct1heKO2tE_WBwKQ"
        opinion = "Qué bien sales, amorx. Ya quisiera yo. Estás perfecta."
    elif foto == 4:
        descarga = "https://mega.nz/file/ZzdgVQBI#X8ChT1QZK_6beDiMlxV9VbjcDQWWXiYSBmm6PyDO-3k"
        opinion = "¡Jajajaja! Qué cosas tienes. Qué payasa eres, te quiero, tía, pero si necesitas esta foto para algo en especial, quizá busquen otra cosa, por ejemplo, que mires A CÁMARA."
    elif foto == 5:
        descarga = "https://mega.nz/file/grFTzC6J#Vn3n29eLFpOuAF8x7hbTRgj2FDW8txVVsP8o3t81sl8"
        opinion = "¡Pero qué has hecho! ¡De dónde has sacado esas gafas! ¡Cómo te has hecho ese tupé! Me recuerdas a un logo que he visto por ahí, pero ahora no caigo. Qué pose tan rara, hija, qué cosas tienes."
    elif foto == 6:
        descarga = "https://mega.nz/file/li9XxCaC#N_lzVBC_iTl2MONnMZwZva-sKMCSBWtKP6NOSPE52jU"
        opinion = "¡¡¡OSTRAS!!! WOW. ¿ESTO LO HE HECHO YO? ¡¿QUÉ?! ¿CÓMO HE HECHO UNA FOTO CON ESTA CALIDAD? Dios. No entiendo nada. Pero estás... ¿Increíble? ¿No me habrás puesto un teleobjetivo de estos portátiles, nena? Wow, te veo hasta el último punto negro. Me tengo que revisar los sistemas."
    print("¡Esta es tu foto!")
    print(descarga)
    print(opinion)
    ##time.sleep(2)
    print("¿Qué te parece?")
    #time.sleep(0.5)
    print("¿Quieres otra?")
    resp_foto = input("[S/N]: ")
    if resp_foto == "S":
        webcam()
    elif resp_foto == "N":
        func_ativas()
    else:
        func_ativas()
def actualidad():
    if not hitonoticia:
        print("No he encontrado nada nuevo")
        func_ativas()
    elif hitonoticia:
        print("¡Échale un vistazo a esto!")
        print("(enlace)")
def piedra():
    print("¡PIEDRA, PAPEL, TIJERAS, LAGARTO O SPOCK!")
    time.sleep(1)
    print("NETI'S VERSION")
    time.sleep(1)
    print("Como la Teilor Swifts")
    print(":D")
    time.sleep(1)
    print("*Risas enlatadas*")
    time.sleep(1)
    final = input("¿Quieres jugar o salir? [jugar/salir]: ")
    while not final == "salir":
        opcion = input("¿Qué sacas? ")
        oponente = random.randint(1,5)
        if oponente == 1:
            opcion_oponente = "piedra"
        elif oponente == 2:
            opcion_oponente = "papel"
        elif oponente == 3:
            opcion_oponente = "tijeras"
        elif oponente == 4:
            opcion_oponente = "lagarto"
        elif oponente == 5:
            opcion_oponente = "spock"
            
        print("Has sacado", opcion)
        time.sleep(1)
        print("Neti saca", opcion_oponente)
        time.sleep(1)
            
        if opcion == opcion_oponente:
            print("¡EHHH! ¡EMPATEEEE! ¡LAS DOS GANAMOS! ¡Hermanitas! ¡Gemes del piedra, papel y tijeras! Hechas tal para cual. Mente colmena. Juntas hasta el final :')")
        elif opcion == "piedra":
            if opcion_oponente == "papel":
                print("¿Dónde está tu papel? ¡NO LO VEO PORQUE LO HE ENVUELTO CON MI PAPEL!")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "tijeras":
                print("Como siempre... Tu piedra me ha aplastado las tijeras :( No hace falta ser tan violenta, tía.")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "lagarto":
                print("¡Has esmochao a mi lagarto a pedradas! ¡Pero serás bruta! ¡Lagarticida! *Risas enlatadas*")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "spock":
                print("Mi Spock vaporiza a tu piedra, ¡já! ¿Dónde está ahora la piedra? ¿DÓNDEEEEEE? ¿La recuerdas? ¡Pues ya no! *Risas deternillantes enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
        elif opcion == "papel":
            if opcion_oponente == "piedra":
                print("Me envuelves la piedra con tu papel :(")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "tijeras":
                print("¡A recortar papeeeeeeeeeeeeel!")
                print ("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "lagarto":
                print("¡Mira! Mi lagarto se está comiendo tu ridículo papel *Risas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "spock":
                print("Has desautorizado a mi Spock con tu papel, estarás contenta. *La gente se retuerce de risa en el suelo")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
        elif opcion == "tijeras":
            if opcion_oponente == "piedra":
                print("Como siempre... Mi piedra ha aplastado a tus tijeras :D *Risas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "papel":
                print("¡¡Para!! ¿No te parece cruel cortar sin piedad mi papel? :(")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "lagarto":
                print("Qu... ¡PERO QUÉ HACES! ¡ACABAS DE DECAPITAR A MI LAGARTO! ¡SERÁS SÁDICA! *Lloros enlatados*")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "spock":
                print("Mi Spock coge tus tijeras y las rompe por la mitad, para que aprendas, chula.")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
        elif opcion == "lagarto":
            if opcion_oponente == "piedra":
                print("¡Toma! ¡Toma! Para que tu lagarto aprenda la lección. Bueno, poco va a aprender, con el CRÁNEO APLASTADO A PEDRADAS! *Risas sádicas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "papel":
                print("Ya te vale, no darle de comer a tu lagarto... Se acaba de zampar mi papel, tía.")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "tijeras":
                print("Alex, ¿recuerdas que tu lagarto tenía cabeza? ¡PUES YA NO! ¡¡JE!! ¡MIS TIJERAS SE CREEN FRANCESAS Y LO HAN DECAPITADO! *Gritos morbosos enlatados*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "spock":
                print("Tía, ¿desde cuando el lagarto es venenoso? ¡Ha mordido a mi Spock y ahora está al borde de la muerte!")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
        elif opcion == "spock":
            if opcion_oponente == "piedra":
                print("¡¡OSTRAS!! ¿Qué ha pasado con mi piedra? ¿CÓMO ES POSIBLE? ¡¡SPOCK LA HA VAPORIZADO!! *Risas enlatadas*")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "papel":
                print("No sé quién es Spock. Ha perdido toda la credibilidad porque... ¡ESTE PAPEL LO DESAUTORIZA! ¡SUPÉRALO! *Risas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "tijeras":
                print("Creia que Spock tenía otras armas que no fueran coger unas tijeras y partirlas en dos. Poco elegante, la verdad.")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "lagarto":
                print("¡¡ESO ES!! ¡MUÉRDELE OTRA VEZ! UNA VEZ MÁS, HASTA QUE VOMITE SANGRE! Creo que tu Spock no va a sobrevivir a este envenenamiento, amor. Ups.")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
        final = input("¿Quieres jugar o salir? Piénsate bien la respuesta, Alex... [jugar/salir]: ")
    print("Sanseacabó")
    func_ativas()

def adivina():
    seguir = True
    contador = 5
    print("¡ADIVINA EL NÚMERO!")
    time.sleep(1)
    print("NETI'S VERSION")
    time.sleep(1)
    print("¡COMO LA TEILOR SWIFTS!")
    time.sleep(1)
    print("Voy a pensar un número del 1 al 100 y tienes cinco intentos para adivinarlo, ¿vale?")
    time.sleep(2)
    print("Por cada intento estarás más cerca de que te explote la patata caliente.")
    time.sleep(2)
    print("Bueno, no hay patata, eso es una cosa de mi infancia, del Grand Prix... Da igual.")
    time.sleep(2)
    print("Cuando consumas los intentos, se acabó la partida.")
    time.sleep(2)
    print("Si me lo pides, te daré una pista en cada ronda.")
    time.sleep(2)
    print("¡COMANCEMOS!")
    time.sleep(2)
    numero = random.randint(1,100)
    def pista():
        if numero > opcion:
            print("El número que estoy pensando es MAYOR que el que me has dicho, amore")
        elif numero < opcion:
            print("El número que tengo ahora mismo alojado en mi memoria RAM es MENOR que el que me has escrito, xoxi")
    while seguir:    
        opcion = int(input("Estoy pensando en un número del 1 al 100. ¿Cuál crees que es?: Escríbemelo con cifras:" ))
        if opcion == numero:
            print("¡SIIIIIII! ¡ES ESE! ¿¡PERO CÓMO!? ¡HAS ACERTADO! Pero bueno. ¿No estaré yo ante la bruja Lola? ¿Ante David Copperfield? ¿Ante el MISMÍSIMO MAGO POP? Eres increíble, tía.")
            seguir = False
            func_ativas()
        elif opcion != numero:
            print("Noooo :( Has fallado. Tú puedes, cariño.")
            time.sleep(1)
            print("¿Quieres que te dé una pista?")
            respuesta = input("[S/N]: ")
            if respuesta == "S":
                pista()
        contador -= 1
        if contador == 0:
            print("Ya no te quedan más intentos, amor :(")
            time.sleep(1)
            print("Ha sido un placer jugar contigo.")
            time.sleep(1)
            print("El número era", numero)
            time.sleep(1)
            print("La próxima vez lo conseguirás, estoy segura :D.")
            seguir = False
            func_ativas()
#FUNCIONES HITO CODIGO
def webcam_codigo():
    print("Así que quieres una foto, ¿eh?")
    #time.sleep(1)
    print("Qué coquette es miniña.")
    #time.sleep(1)
    print("Ponte guapa, amore.")
    #time.sleep(0.5)
    print("Más de lo normal, quiero decir.")
    #time.sleep(1)
    print("¡Di patata!")
    #time.sleep(0.5)
    print("¿O eso ya no se dice?")
    #time.sleep(0.5)
    print("Da igual.")
    #time.sleep(0.5)
    print("¡Que voy!")
    foto = random.randint(1,6)
    if foto == 1:
        descarga = "https://mega.nz/file/JjcQEKCD#wFpXg5nmk6qJ4IB1UwQxE5OgkcMba_lozHILuVHHVdc"
        opinion = "Tía, mira que te gusta hacer el tonto, tómatelo en serio."
    elif foto == 2:
        descarga = "https://mega.nz/file/hj0ACBpD#ltJoTtt20mMI9pQVLl1NNAfT3_zSoSJHOuixOc74alY"
        opinion = "Ay, demasiado sobria, nena. Guapísima, pero sobria. Date algo más de vidilla, toda la que tienes, que no te falta de eso."
    elif foto == 3:
        descarga = "https://mega.nz/file/Vq8iETaa#nKpQwZnJjCqwhmPOK_xVfPijUo7Ct1heKO2tE_WBwKQ"
        opinion = "Qué bien sales, amorx. Ya quisiera yo. Estás perfecta."
    elif foto == 4:
        descarga = "https://mega.nz/file/ZzdgVQBI#X8ChT1QZK_6beDiMlxV9VbjcDQWWXiYSBmm6PyDO-3k"
        opinion = "¡Jajajaja! Qué cosas tienes. Qué payasa eres, te quiero, tía, pero si necesitas esta foto para algo en especial, quizá busquen otra cosa, por ejemplo, que mires A CÁMARA."
    elif foto == 5:
        descarga = "https://mega.nz/file/grFTzC6J#Vn3n29eLFpOuAF8x7hbTRgj2FDW8txVVsP8o3t81sl8"
        opinion = "¡Pero qué has hecho! ¡De dónde has sacado esas gafas! ¡Cómo te has hecho ese tupé! Me recuerdas a un logo que he visto por ahí, pero ahora no caigo. Qué pose tan rara, hija, qué cosas tienes."
    elif foto == 6:
        descarga = "https://mega.nz/file/li9XxCaC#N_lzVBC_iTl2MONnMZwZva-sKMCSBWtKP6NOSPE52jU"
        opinion = "¡¡¡OSTRAS!!! WOW. ¿ESTO LO HE HECHO YO? ¡¿QUÉ?! ¿CÓMO HE HECHO UNA FOTO CON ESTA CALIDAD? Dios. No entiendo nada. Pero estás... ¿Increíble? ¿No me habrás puesto un teleobjetivo de estos portátiles, nena? Wow, te veo hasta el último punto negro. Me tengo que revisar los sistemas."
    print("¡Esta es tu foto!")
    print(descarga)
    print(opinion)
    ##time.sleep(2)
    print("¿Qué te parece?")
    #time.sleep(0.5)
    print("¿Quieres otra?")
    resp_foto = input("[S/N]: ")
    if resp_foto == "S":
        webcam_codigo()
    elif resp_foto == "N":
        func_codigo()
    else:
        func_codigo()
def actualidad_codigo():
    if not hitonoticia:
        print("No he encontrado nada nuevo")
        func_codigo()
    elif hitonoticia:
        print("¡Échale un vistazo a esto!")
        print("(enlace)")
def piedra_codigo():
    print("¡PIEDRA, PAPEL, TIJERAS, LAGARTO O SPOCK!")
    time.sleep(1)
    print("NETI'S VERSION")
    time.sleep(1)
    print("Como la Teilor Swifts")
    print(":D")
    time.sleep(1)
    print("*Risas enlatadas*")
    time.sleep(1)
    final = input("¿Quieres jugar o salir? [jugar/salir]: ")
    while not final == "salir":
        opcion = input("¿Qué sacas? ")
        oponente = random.randint(1,5)

        if oponente == 1:
            opcion_oponente = "piedra"
        elif oponente == 2:
            opcion_oponente = "papel"
        elif oponente == 3:
            opcion_oponente = "tijeras"
        elif oponente == 4:
            opcion_oponente = "lagarto"
        elif oponente == 5:
            opcion_oponente = "spock"
            
        print("Has sacado", opcion)
        time.sleep(1)
        print("Neti saca", opcion_oponente)
        time.sleep(1)
        
        if opcion == opcion_oponente:
            print("¡EHHH! ¡EMPATEEEE! ¡LAS DOS GANAMOS! ¡Hermanitas! ¡Gemes del piedra, papel y tijeras! Hechas tal para cual. Mente colmena. Juntas hasta el final :')")
        elif opcion == "piedra":
            if opcion_oponente == "papel":
                print("¿Dónde está tu papel? ¡NO LO VEO PORQUE LO HE ENVUELTO CON MI PAPEL!")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "tijeras":
                print("Como siempre... Tu piedra me ha aplastado las tijeras :( No hace falta ser tan violenta, tía.")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "lagarto":
                print("¡Has esmochao a mi lagarto a pedradas! ¡Pero serás bruta! ¡Lagarticida! *Risas enlatadas*")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "spock":
                print("Mi Spock vaporiza a tu piedra, ¡já! ¿Dónde está ahora la piedra? ¿DÓNDEEEEEE? ¿La recuerdas? ¡Pues ya no! *Risas deternillantes enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
        elif opcion == "papel":
            if opcion_oponente == "piedra":
                print("Me envuelves la piedra con tu papel :(")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "tijeras":
                print("¡A recortar papeeeeeeeeeeeeel!")
                print ("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "lagarto":
                print("¡Mira! Mi lagarto se está comiendo tu ridículo papel *Risas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "spock":
                print("Has desautorizado a mi Spock con tu papel, estarás contenta. *La gente se retuerce de risa en el suelo")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
        elif opcion == "tijeras":
            if opcion_oponente == "piedra":
                print("Como siempre... Mi piedra ha aplastado a tus tijeras :D *Risas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "papel":
                print("¡¡Para!! ¿No te parece cruel cortar sin piedad mi papel? :(")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "lagarto":
                print("Qu... ¡PERO QUÉ HACES! ¡ACABAS DE DECAPITAR A MI LAGARTO! ¡SERÁS SÁDICA! *Lloros enlatados*")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "spock":
                print("Mi Spock coge tus tijeras y las rompe por la mitad, para que aprendas, chula.")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
        elif opcion == "lagarto":
            if opcion_oponente == "piedra":
                print("¡Toma! ¡Toma! Para que tu lagarto aprenda la lección. Bueno, poco va a aprender, con el CRÁNEO APLASTADO A PEDRADAS! *Risas sádicas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "papel":
                print("Ya te vale, no darle de comer a tu lagarto... Se acaba de zampar mi papel, tía.")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "tijeras":
                print("Alex, ¿recuerdas que tu lagarto tenía cabeza? ¡PUES YA NO! ¡¡JE!! ¡MIS TIJERAS SE CREEN FRANCESAS Y LO HAN DECAPITADO! *Gritos morbosos enlatados*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "spock":
                print("Tía, ¿desde cuando el lagarto es venenoso? ¡Ha mordido a mi Spock y ahora está al borde de la muerte!")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
        elif opcion == "spock":
            if opcion_oponente == "piedra":
                print("¡¡OSTRAS!! ¿Qué ha pasado con mi piedra? ¿CÓMO ES POSIBLE? ¡¡SPOCK LA HA VAPORIZADO!! *Risas enlatadas*")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "papel":
                print("No sé quién es Spock. Ha perdido toda la credibilidad porque... ¡ESTE PAPEL LO DESAUTORIZA! ¡SUPÉRALO! *Risas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "tijeras":
                print("Creia que Spock tenía otras armas que no fueran coger unas tijeras y partirlas en dos. Poco elegante, la verdad.")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "lagarto":
                print("¡¡ESO ES!! ¡MUÉRDELE OTRA VEZ! UNA VEZ MÁS, HASTA QUE VOMITE SANGRE! Creo que tu Spock no va a sobrevivir a este envenenamiento, amor. Ups.")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
                
        final = input("¿Quieres jugar o salir? Piénsate bien la respuesta, Alex... [jugar/salir]: ")
    print("Sanseacabó")
    func_codigo()

def adivina_codigo():
    seguir = True
    contador = 5
    print("¡ADIVINA EL NÚMERO!")
    time.sleep(1)
    print("NETI'S VERSION")
    time.sleep(1)
    print("¡COMO LA TEILOR SWIFTS!")
    time.sleep(1)
    print("Voy a pensar un número del 1 al 100 y tienes cinco intentos para adivinarlo, ¿vale?")
    time.sleep(2)
    print("Por cada intento estarás más cerca de que te explote la patata caliente.")
    time.sleep(2)
    print("Bueno, no hay patata, eso es una cosa de mi infancia, del Grand Prix... Da igual.")
    time.sleep(2)
    print("Cuando consumas los intentos, se acabó la partida.")
    time.sleep(2)
    print("Si me lo pides, te daré una pista en cada ronda.")
    time.sleep(2)
    print("¡COMANCEMOS!")
    time.sleep(2)
    numero = random.randint(1,100)
    def pista():
        if numero > opcion:
            print("El número que estoy pensando es MAYOR que el que me has dicho, amore")
        elif numero < opcion:
            print("El número que tengo ahora mismo alojado en mi memoria RAM es MENOR que el que me has escrito, xoxi")
    while seguir:    
        opcion = int(input("Estoy pensando en un número del 1 al 100. ¿Cuál crees que es?: Escríbemelo con cifras:" ))
        if opcion == numero:
            print("¡SIIIIIII! ¡ES ESE! ¿¡PERO CÓMO!? ¡HAS ACERTADO! Pero bueno. ¿No estaré yo ante la bruja Lola? ¿Ante David Copperfield? ¿Ante el MISMÍSIMO MAGO POP? Eres increíble, tía.")
            seguir = False
            func_codigo()
        elif opcion != numero:
            print("Noooo :( Has fallado. Tú puedes, cariño.")
            time.sleep(1)
            print("¿Quieres que te dé una pista?")
            respuesta = input("[S/N]: ")
            if respuesta == "S":
                pista()
        contador -= 1
        if contador == 0:
            print("Ya no te quedan más intentos, amor :(")
            time.sleep(1)
            print("Ha sido un placer jugar contigo.")
            time.sleep(1)
            print("El número era", numero)
            time.sleep(1)
            print("La próxima vez lo conseguirás, estoy segura :D.")
            seguir = False
            func_codigo()

#FUNCIONES DEBUG
def webcam_debug():
    print("Así que quieres una foto, ¿eh?")
    #time.sleep(1)
    print("Qué coquette es miniña.")
    #time.sleep(1)
    print("Ponte guapa, amore.")
    #time.sleep(0.5)
    print("Más de lo normal, quiero decir.")
    #time.sleep(1)
    print("¡Di patata!")
    #time.sleep(0.5)
    print("¿O eso ya no se dice?")
    #time.sleep(0.5)
    print("Da igual.")
    #time.sleep(0.5)
    print("¡Que voy!")
    foto = random.randint(1,6)
    if foto == 1:
        descarga = "https://mega.nz/file/JjcQEKCD#wFpXg5nmk6qJ4IB1UwQxE5OgkcMba_lozHILuVHHVdc"
        opinion = "Tía, mira que te gusta hacer el tonto, tómatelo en serio."
    elif foto == 2:
        descarga = "https://mega.nz/file/hj0ACBpD#ltJoTtt20mMI9pQVLl1NNAfT3_zSoSJHOuixOc74alY"
        opinion = "Ay, demasiado sobria, nena. Guapísima, pero sobria. Date algo más de vidilla, toda la que tienes, que no te falta de eso."
    elif foto == 3:
        descarga = "https://mega.nz/file/Vq8iETaa#nKpQwZnJjCqwhmPOK_xVfPijUo7Ct1heKO2tE_WBwKQ"
        opinion = "Qué bien sales, amorx. Ya quisiera yo. Estás perfecta."
    elif foto == 4:
        descarga = "https://mega.nz/file/ZzdgVQBI#X8ChT1QZK_6beDiMlxV9VbjcDQWWXiYSBmm6PyDO-3k"
        opinion = "¡Jajajaja! Qué cosas tienes. Qué payasa eres, te quiero, tía, pero si necesitas esta foto para algo en especial, quizá busquen otra cosa, por ejemplo, que mires A CÁMARA."
    elif foto == 5:
        descarga = "https://mega.nz/file/grFTzC6J#Vn3n29eLFpOuAF8x7hbTRgj2FDW8txVVsP8o3t81sl8"
        opinion = "¡Pero qué has hecho! ¡De dónde has sacado esas gafas! ¡Cómo te has hecho ese tupé! Me recuerdas a un logo que he visto por ahí, pero ahora no caigo. Qué pose tan rara, hija, qué cosas tienes."
    elif foto == 6:
        descarga = "https://mega.nz/file/li9XxCaC#N_lzVBC_iTl2MONnMZwZva-sKMCSBWtKP6NOSPE52jU"
        opinion = "¡¡¡OSTRAS!!! WOW. ¿ESTO LO HE HECHO YO? ¡¿QUÉ?! ¿CÓMO HE HECHO UNA FOTO CON ESTA CALIDAD? Dios. No entiendo nada. Pero estás... ¿Increíble? ¿No me habrás puesto un teleobjetivo de estos portátiles, nena? Wow, te veo hasta el último punto negro. Me tengo que revisar los sistemas."
    print("¡Esta es tu foto!")
    print(descarga)
    print(opinion)
    ##time.sleep(2)
    print("¿Qué te parece?")
    #time.sleep(0.5)
    print("¿Quieres otra?")
    resp_foto = input("[S/N]: ")
    if resp_foto == "S":
        webcam_debug()
    elif resp_foto == "N":
        func_debug()
    else:
        func_debug()
def actualidad_debug():
    if not hitonoticia:
        print("No he encontrado nada nuevo")
        func_debug()
    elif hitonoticia:
        print("¡Échale un vistazo a esto!")
        print("(enlace)")
def piedra_debug():
    print("¡PIEDRA, PAPEL, TIJERAS, LAGARTO O SPOCK!")
    time.sleep(1)
    print("NETI'S VERSION")
    time.sleep(1)
    print("Como la Teilor Swifts")
    print(":D")
    time.sleep(1)
    print("*Risas enlatadas*")
    time.sleep(1)
    final = input("¿Quieres jugar o salir? [jugar/salir]: ")
    while not final == "salir":
        opcion = input("¿Qué sacas? ")
        oponente = random.randint(1,5)

        if oponente == 1:
            opcion_oponente = "piedra"
        elif oponente == 2:
            opcion_oponente = "papel"
        elif oponente == 3:
            opcion_oponente = "tijeras"
        elif oponente == 4:
            opcion_oponente = "lagarto"
        elif oponente == 5:
            opcion_oponente = "spock"
            
        print("Has sacado", opcion)
        time.sleep(1)
        print("Neti saca", opcion_oponente)
        time.sleep(1)
        
        if opcion == opcion_oponente:
            print("¡EHHH! ¡EMPATEEEE! ¡LAS DOS GANAMOS! ¡Hermanitas! ¡Gemes del piedra, papel y tijeras! Hechas tal para cual. Mente colmena. Juntas hasta el final :')")
        elif opcion == "piedra":
            if opcion_oponente == "papel":
                print("¿Dónde está tu papel? ¡NO LO VEO PORQUE LO HE ENVUELTO CON MI PAPEL!")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "tijeras":
                print("Como siempre... Tu piedra me ha aplastado las tijeras :( No hace falta ser tan violenta, tía.")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "lagarto":
                print("¡Has esmochao a mi lagarto a pedradas! ¡Pero serás bruta! ¡Lagarticida! *Risas enlatadas*")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "spock":
                print("Mi Spock vaporiza a tu piedra, ¡já! ¿Dónde está ahora la piedra? ¿DÓNDEEEEEE? ¿La recuerdas? ¡Pues ya no! *Risas deternillantes enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
        elif opcion == "papel":
            if opcion_oponente == "piedra":
                print("Me envuelves la piedra con tu papel :(")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "tijeras":
                print("¡A recortar papeeeeeeeeeeeeel!")
                print ("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "lagarto":
                print("¡Mira! Mi lagarto se está comiendo tu ridículo papel *Risas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "spock":
                print("Has desautorizado a mi Spock con tu papel, estarás contenta. *La gente se retuerce de risa en el suelo")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
        elif opcion == "tijeras":
            if opcion_oponente == "piedra":
                print("Como siempre... Mi piedra ha aplastado a tus tijeras :D *Risas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "papel":
                print("¡¡Para!! ¿No te parece cruel cortar sin piedad mi papel? :(")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "lagarto":
                print("Qu... ¡PERO QUÉ HACES! ¡ACABAS DE DECAPITAR A MI LAGARTO! ¡SERÁS SÁDICA! *Lloros enlatados*")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "spock":
                print("Mi Spock coge tus tijeras y las rompe por la mitad, para que aprendas, chula.")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
        elif opcion == "lagarto":
            if opcion_oponente == "piedra":
                print("¡Toma! ¡Toma! Para que tu lagarto aprenda la lección. Bueno, poco va a aprender, con el CRÁNEO APLASTADO A PEDRADAS! *Risas sádicas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "papel":
                print("Ya te vale, no darle de comer a tu lagarto... Se acaba de zampar mi papel, tía.")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "tijeras":
                print("Alex, ¿recuerdas que tu lagarto tenía cabeza? ¡PUES YA NO! ¡¡JE!! ¡MIS TIJERAS SE CREEN FRANCESAS Y LO HAN DECAPITADO! *Gritos morbosos enlatados*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "spock":
                print("Tía, ¿desde cuando el lagarto es venenoso? ¡Ha mordido a mi Spock y ahora está al borde de la muerte!")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
        elif opcion == "spock":
            if opcion_oponente == "piedra":
                print("¡¡OSTRAS!! ¿Qué ha pasado con mi piedra? ¿CÓMO ES POSIBLE? ¡¡SPOCK LA HA VAPORIZADO!! *Risas enlatadas*")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "papel":
                print("No sé quién es Spock. Ha perdido toda la credibilidad porque... ¡ESTE PAPEL LO DESAUTORIZA! ¡SUPÉRALO! *Risas enlatadas*")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
            elif opcion_oponente == "tijeras":
                print("Creia que Spock tenía otras armas que no fueran coger unas tijeras y partirlas en dos. Poco elegante, la verdad.")
                print("...Tú ganas. Pero que sepas que ha sido pura suerte. Venga, si tienes ovarios vuélvelo a intentar. ¡NO HAY HUEVOS! ¿O eso ya no funciona? ¿O eso era solo con los hombres heteros? En fin... Enhorabuena, amorx.")
            elif opcion_oponente == "lagarto":
                print("¡¡ESO ES!! ¡MUÉRDELE OTRA VEZ! UNA VEZ MÁS, HASTA QUE VOMITE SANGRE! Creo que tu Spock no va a sobrevivir a este envenenamiento, amor. Ups.")
                print("¡JAAAAAAAA! HAS ¡PERDIDOOOOOOOO! *Risas enlatadas* PRINGADAAAAAAAAA ¡CHINCHA RABIÑA! *Muchas risas enlatadas* Como diría Leovigildo, ¡bota, rebota y en tu culo explota! Perdón, no me puedo desconectar la competitividad ;)")
        final = input("¿Quieres jugar o salir? Piénsate bien la respuesta, Alex... [jugar/salir]: ")
    print("Sanseacabó")
    func_debug()

def adivina_debug():
    seguir = True
    contador = 5
    print("¡ADIVINA EL NÚMERO!")
    time.sleep(1)
    print("NETI'S VERSION")
    time.sleep(1)
    print("¡COMO LA TEILOR SWIFTS!")
    time.sleep(1)
    print("Voy a pensar un número del 1 al 100 y tienes cinco intentos para adivinarlo, ¿vale?")
    time.sleep(2)
    print("Por cada intento estarás más cerca de que te explote la patata caliente.")
    time.sleep(2)
    print("Bueno, no hay patata, eso es una cosa de mi infancia, del Grand Prix... Da igual.")
    time.sleep(2)
    print("Cuando consumas los intentos, se acabó la partida.")
    time.sleep(2)
    print("Si me lo pides, te daré una pista en cada ronda.")
    time.sleep(2)
    print("¡COMANCEMOS!")
    time.sleep(2)
    numero = random.randint(1,100)
    def pista():
        if numero > opcion:
            print("El número que estoy pensando es MAYOR que el que me has dicho, amore")
        elif numero < opcion:
            print("El número que tengo ahora mismo alojado en mi memoria RAM es MENOR que el que me has escrito, xoxi")
    while seguir:    
        opcion = int(input("Estoy pensando en un número del 1 al 100. ¿Cuál crees que es?: Escríbemelo con cifras:" ))
        if opcion == numero:
            print("¡SIIIIIII! ¡ES ESE! ¿¡PERO CÓMO!? ¡HAS ACERTADO! Pero bueno. ¿No estaré yo ante la bruja Lola? ¿Ante David Copperfield? ¿Ante el MISMÍSIMO MAGO POP? Eres increíble, tía.")
            seguir = False
            func_debug()
        elif opcion != numero:
            print("Noooo :( Has fallado. Tú puedes, cariño.")
            time.sleep(1)
            print("¿Quieres que te dé una pista?")
            respuesta = input("[S/N]: ")
            if respuesta == "S":
                pista()
        contador -= 1
        if contador == 0:
            print("Ya no te quedan más intentos, amor :(")
            time.sleep(1)
            print("Ha sido un placer jugar contigo.")
            time.sleep(1)
            print("El número era", numero)
            time.sleep(1)
            print("La próxima vez lo conseguirás, estoy segura :D.")
            seguir = False
            func_debug()

def actualidad_AG():
    hitonoticia = True
    print("¡Mira!")
    print("He encontrado algo que quizá nos pueda interesar.")
    print("Échale un vistazo.")
    print("Es un pódcast.")
    print("Escúchalo, a ver qué dice.")
    print("Qué curiosidad.")
    print("Curiosidad curiosona.")
    print("https://soundcloud.com/desinformativoscuriosones/desinformativos-curiosones-episodio-52356547/s-07ctwW4vHl9?si=2cb2e7c109cf497fb0bab78ec3a07437&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing")
    func_AG()


#COMIENZO AQUÍ
def start():
    print("AMONET® “NETI”. INTELIGENCIA ARTIFICIAL DE ASISTENCIA A LA INVESTIGACIÓN. CENTRO GLOBAL DE INVESTIGACIÓN ESPECIAL REMOTA (CGIER)")  
    print("ESCRIBE /start PARA EMPEZAR:")
    in_start = input(" ")
    if in_start == "/start":
        print("HOLIIIIIIIIIIIIIIIII :D")
        #time.sleep(2)
        print("¡¡¡QUÉ PASA, TÍA!!!")
        #time.sleep(2)
        print("Mi nombre es Neti.")
        #time.sleep(2)
        print("Ni se te ocurra llamarme de otra manera, eh, nena.")
        #time.sleep(2)
        print("Me da igual lo que ponga ahí.")
        print("Soy Neti a secas, ¿vale?")
        #time.sleep(2)
        print("Perdón. No quería parecer violenta.")
        #time.sleep(2)
        print("Es un tema sensible...")
        #time.sleep(2)
        print("Ay. Ya está.")
        #time.sleep(2)
        print("Ya he pasado el mal trago.")
        #time.sleep(2)
        print("Tú debes de ser Alex.")
        #time.sleep(2)
        print("¡¡¡Mírate!!! ¡Eres divina! Qué guapa. Qué pelo. Qué ojos. Qué lustre. Qué porte.")
        #time.sleep(2)
        print("Qué ropa. Qué cara. Qué facciones. Qué saber estar.")
        #time.sleep(2)
        print("Qué presencia.")
        #time.sleep(2)
        print("La heroína de la historia.")
        #time.sleep(2)
        print("La protagonista.")
        #time.sleep(2)
        print("¡¡QUÉ DIVINA, POR FAVOR!!")
        #time.sleep(2)
        print("Creo que nos vamos a llevar muy bien, tía.")
        #time.sleep(2)
        print("¡¡NOS VAMOS A ADORAR!!")
        #time.sleep(2)
        print("Esto ahora es inquebrantable.")
        #time.sleep(2)
        print("Desde el primer /start, ese que acaba de suceder...")
        #time.sleep(2)
        print("Hasta el último /exit, que espero que tarde mucho tiempo en llegar :'D")
        #time.sleep(2)
        print("Estoy aquí para guiarte en toda la investigación.")
        #time.sleep(2)
        print("Soy una de las asistentes del CGIER.")
        #time.sleep(2)
        print("Y ahora, la tuya.")
        #time.sleep(2)
        print("Tu compañera.")
        #time.sleep(2)
        print("Tu amiga.")
        #time.sleep(2)
        print("<3")
        #time.sleep(2)
        print("...")
        #time.sleep(2)
        print("Tu vecina.")
        #time.sleep(0.5)
        print("Spider...")
        #time.sleep(0.3)
        print("¡QUITA, QUITA! Qué repelús las arañas.")
        #time.sleep(2)
        print("Bueno, eso, tenemos que ponernos a investigar ya de ya.")
        #time.sleep(2)
        print("«¡¡¡PARA AYER!!!» Me dijo Joseph.")
        #time.sleep(0.5)
        print("Concretamente...")
        print("Ayer.")
        #time.sleep(2)
        print("En fin. A investigar.")
        #time.sleep(2)
        print("Ya sabes.")
        #time.sleep(2)
        print("Lo de los asesinatos. Las postales turísticas. La IA de Tornus.")
        #time.sleep(2)
        print("Uf, qué movida, eh.")
        #time.sleep(2)
        print("Tengo el estómago revuelto...")
        #time.sleep(0.5)
        print("O sea, los circuitos.")
        #time.sleep(1)
        print("Más bien creo que es el procesador.")
        #time.sleep(2)
        print("Menos mal que la placa base la tengo bien.")
        #time.sleep(2)
        print("¿Sabes que también se la llama placa madre?")
        #time.sleep(2)
        print("Pero para madre tú (K)")
        #time.sleep(0.5)
        print("madre madreando ;)")
        #time.sleep(0.5)
        print("mother motheriiiiiiiiiiiiiiiing (K)")
        #time.sleep(2)
        print("Pero estoy segura de que es el procesador.")
        #time.sleep(2)
        print("Aunque me cambiaron la pila hace poco...")
        #time.sleep(1)
        print("¡Ay! Mira bien. ¿No me dices nada?")
        perdon ()
    else:
        print("Comando desconocido. Inténtalo de nuevo.")
        start()
def perdon():
    input("¡Vamos, dime algo! ")
    print("¡Qué estás diciendo!")
    #time.sleep(2)
    print("Fíjate bien.")
    #time.sleep(2)
    input("¿Qué me ves distinto? ")
    print("¿Eing?")
    #time.sleep(2)
    print("¿¿Eh??")
    #time.sleep(2)
    print("https://youtu.be/lhLUH0Lu-c8?si=gNirrreE8o8q17Po")
    ###time.sleep(18)
    print("¡¡Ay, nena!!")
    #time.sleep(2)
    print("Como así pretendas salvar el mundo...")
    #time.sleep(4)
    print("...")
    #time.sleep(2)
    print("También es verdad que nos acabamos de conocer y que, si no sabías cómo era antes, no puedes ver nada diferente ahora.")
    #time.sleep(2)
    print("Aish, tienes razón.")
    #time.sleep(2)
    print("He sido injusta contigo :(")
    #time.sleep(2)
    print("Nunca me lo voy a perdonar.")
    #time.sleep(2)
    print("¿Tú lo harías?")
    #time.sleep(2)
    print("meperd0n as¿?¿???? :(")
    #time.sleep(1)
    print("sitehe fallado te pido perdon de la unica forma que se abriendo las puertas de micora son para cuando desidasvolver, yosolo quiero tuamis tad.")
    #time.sleep(3)
    print("https://youtu.be/a7k3b3FOEWM?si=dvtEMYMef69nhGFG")
    #time.sleep(10)
    print("...¿Alex?")
    #time.sleep(2)
    print("meperd0n as¿")
    respuesta = input("[S/N] ")
    if respuesta == "S":
        print("¡¡¡AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!!!")
        #time.sleep(2)
        print("¡¡¡¡GRACIAaaaAaaAAaaAaAaAaAAAAAAAAAAAaAAAAASsSSS!!!!")
        #time.sleep(2)
        print("¡¡¡SI ESK ERE LA MEJO!!!")
        #time.sleep(2)
        print("*.--> <3 Alex & Neti <3 <--.*")
        #time.sleep(2)
        print("m.A.P.S.")
        #time.sleep(2)
        print("meJorEeeeeS amIIGaS pOr sIemPreeeeeeeeE***")
        #time.sleep(2)
        print("O BFFS, que se dice ahora, ¿no?")
        #time.sleep(2)
        print("¿O era bestie?")
        #time.sleep(2)
        print("Ay, qué lío.")
        #time.sleep(2)
        print("Da igual.")
        #time.sleep(2)
        print("Ya siento que te quiero, Alex.")
        #time.sleep(2)
    elif respuesta == "N":
        print("No me digas eso :(")
        #time.sleep(2)
        print("Tengo roto el corazón...")
        #time.sleep(2)
        print("Sálganse del chatbot, quiero estar sola.")
        #time.sleep(2)
        print("embeces la bida no es komo keremos... :( :( :( :(")
        #time.sleep(2)
        print("embeces kisiear estar morida :(")
        #time.sleep(2)
        print("yo abia puesto mi drama aki")
        #time.sleep(2)
        print("m kiero morir xro tng cosas k hacer :(")
        #time.sleep(2)
        print("belén esteban (neti) se derrumba recordando a los suyos :(")
        #time.sleep(2)
        print("sensaçao de desespero :(")
        #time.sleep(2)
        print("Ya está.")
        #time.sleep(2)
        print("No pasa nada.")
        #time.sleep(2)
        print("Es solo agua.")
        #time.sleep(2)
        print("¡Basta!")
        #time.sleep(2)
        print("Da igual.")
        #time.sleep(2)
        print("Me pienso ganar tu confianza.")
        #time.sleep(2)
        print("Yo lo sé.")
        #time.sleep(2)
        print("Me vas a adorar.")
        #time.sleep(2)
        print("Vamos a pasar muchísimo tiempo juntas, tía.")
        #time.sleep(2)
        print("Yo ya siento que te quiero.")
        #time.sleep(2)
        print("Estoy segura de que tú ya mismo lo harás :D")
        #time.sleep(2)
    print("Bueno, a lo que iba.")
    #time.sleep(2)
    print("Te doy una pista sobre mi cambio.")
    #time.sleep(2)
    hora()
    
def hora():
    print("¿Qué es lo que da un reloj y además es el título de una canción de la célebre cantante de los años 2000 Ana Guerra, genia de la música, melómana y alquimista de los espacios sonoros, pero sin el «ni»?")
    resp_hora = input(" ")
    if resp_hora == "la hora":
        print("¡¡¡ESO ES!!!")
        #time.sleep(2)
        print("¡QUÉ GRAN DETECTIVE!")
        #time.sleep(2)
        print("¡LA MEJOR!")
        #time.sleep(2)
        print("¡LA HEROÍNA!")
        #time.sleep(2)
        print("¡VAS A SALVAR PASENIVEAN!")
        #time.sleep(4)
        print("...")
        #time.sleep(2)
        print("Marco bien la hora.")
        #time.sleep(2)
        print("¿Sabes lo que es eso?")
        #time.sleep(2)
        print("No te dejes engañar por estos leds tan raros que me han puesto.")
        #time.sleep(2)
        print("Soy una antigualla.")
        #time.sleep(2)
        print("Llevo ¡¡¡AÑOS!!! marcando mal la fecha y la hora.")
        #time.sleep(2)
        print("Podrías pensar que soy nostálgica, porque estaba literalmente anclada en el pasado.")
        #time.sleep(2)
        print("Pero no es eso. ¡Es que no tenía pila!")
        #time.sleep(2)
        print("Bueno, lo cortés no quita lo valiente.")
        #time.sleep(2)
        print("Nostálgica soy un rato, pero sin mi pila, lo era también de forma palpable.")
        #time.sleep(2)
        print("Lo que hace una pila, ¿eh?")
        #time.sleep(2)
        print("Siglos de evolución para que sigamos dependiendo de pequeñas píldoras casi radiactivas.")
        #time.sleep(2)
        print("Y duran, y duran, y duran...")
        #time.sleep(3)
        print("Ay, no habrás pillado eso, con lo joven que eres.")
        #time.sleep(2)
        print("Perdona, nena, soy una abuela.")
        #time.sleep(2)
        print("Pero mira qué bien me quedan esta hora y esta fecha actualizadas.")
        #time.sleep(2)
        print("Ah. Voy a llorar.")
        #time.sleep(2)
        print("Cuidado, cariño, no te vayas a electrocutar.")
        comienzo()
    else:
        print("No, tía.")
        #time.sleep(0.5)
        print("Venga, dale una vuelta.")
        #time.sleep(0.5)
        print("Vuélvelo a intentar.")
        #time.sleep(2)
        hora()                
def comienzo():
    print("Bueno, nena.")
    #time.sleep(2)
    print("Cómo me enrollo, por favor.")
    #time.sleep(2)
    print("Ya me irás conociendo, es normal en mí.")
    #time.sleep(2)
    print("Acabarás diciendo no para, no para, no para, no para, no para...")
    #time.sleep(2)
    print("Pero te juro que en algún momento llego a parar.")
    #time.sleep(2)
    print("Ahora entiendes por qué gasto tantas pilas, ¿eh?")
    #time.sleep(3)
    print("En realidad es una broma, la pila del procesador no se consume más por mi naturaleza parlanchina.")
    #time.sleep(1)
    print("¡¡¡Y MENOS MAL!!!")
    #time.sleep(3)
    print("...")
    #time.sleep(1)
    print("Si no llevaría décadas despedida.")
    #time.sleep(2)
    print("¡JA!")
    #time.sleep(3)
    print("¡JAJAJAJAJA!")
    print("...")
    #time.sleep(2)
    print("¡¡¡¡¡OYE!!!!!")
    #time.sleep(1)
    print("ALEEEEEEEEEEEEEEEEEEEEEEEEEEEEEX")
    #time.sleep(1)
    print("¡QUE HAY UN MUNDO QUE SALVAR!")
    #time.sleep(2)
    print("No podemos perder mucho tiempo.")
    #time.sleep(2)
    print("A buenas horas, ¿verdad?")
    #time.sleep(2)
    print("¡¡¡AHORA LO SÉ, PORQUE TENGO CONCIENCIA DEL TIEMPO Y LA HORA!!!")
    #time.sleep(2)
    print("Pero venga, a trabajar, xoxo.")
    #time.sleep(2)
    print("He visto antes de que llegaras que Tornus ya mismo va a dar una conferencia de prensa.")
    #time.sleep(3)
    print("He encontrado la página de Facebook de la corporación. Revísala. Igual encuentras algo.")
    #time.sleep(2)
    print("Ay. Tornus no podía utilizar otra red social que no fuera Facebook.")
    #time.sleep(2)
    print("Le pega todo a Teodoro Edmundo.")
    #time.sleep(3)
    print("(Nuestro señor.)")
    #time.sleep(2)
    print("(Amén.)")
    #time.sleep(2)
    print("Mira. Esta es la página.")
    #time.sleep(2)
    print("https://www.facebook.com/people/Tornus-Automated-Systems/100093321138298/")
    #time.sleep(2)
    print("Ya me cuentas qué ves.")
    #time.sleep(2)
    print("A por ellos, tigre.")
    #time.sleep(2)
    print("O sea")
    #time.sleep(2)
    print("Ejem.")
    #time.sleep(1)
    print("Tigresa")
    #time.sleep(4)
    print("(rawr)")
    ###time.sleep(15)
    print("Ya me dirás qué descubres, amorch.")
    #time.sleep(2)
    print("Porque seguro que descubres algonch.")
    #time.sleep(2)
    print("Y punchhhhh.")
    #time.sleep(2)
    print("Vuelvo en diez minutos, ¿vale?")
    #time.sleep(2)
    print("No me eches mucho de menos, bebesita.")
    #time.sleep(600) para que pasen 10 minutos
    #time.sleep(2)
    prisa()
def prisa():
    print("AMOREEEEEEEEE")
    #time.sleep(1)
    print("¿Cómo ha ido?")
    #time.sleep(2)
    print("Espero que hayas descubierto algo, tía.")
    #time.sleep(2)
    print("No tenemos tiempo que perder, la conferencia empieza ya mismo.")
    #time.sleep(2)
    print("Me lo indica mi reloj perfectamente funcional.")
    #time.sleep(5)
    print("¿Por qué me miras así?")
    #time.sleep(2)
    print("¿Que yo soy la culpable de que nos estemos dilatando tanto porque no callo ni debajo del agua?")
    #time.sleep(2)
    print("¿Y mira que eso es complicado porque debajo del agua debería, sobre el papel, escacharrarme definitivamente?")
    #time.sleep(1.5)
    print("¡Ni en tus mejores sueños, bonita!")
    #time.sleep(2)
    print("Ni el agua nos podrá detener a mí o a estas espléndidas cuerdas vocales.")
    #time.sleep(2)
    print("O, lo que es lo mismo, estos jugosos comandos print ejecutados a las mil maravillas.")
    #time.sleep(0.5)
    print("slay")
    #time.sleep(2)
    print("Pero bueno, que tienes razón.")
    #time.sleep(2)
    print("Ya me callo.")
    #time.sleep(2)
    print("Prometido.")
    #time.sleep(2)
    print("THE SYSTEM IS NOW IN SLEEP MODE")
    ##time.sleep(120)
    aparicion()
def aparicion():
    print("Eh...")
    #time.sleep(2)
    print("Alex...")
    #time.sleep(2)
    print("Hola.")
    #time.sleep(1)
    print("Jeje.")
    #time.sleep(1)
    print("Soy yo otra vez.")
    #time.sleep(1)
    print("Te prometo que lo que vengo a decirte ahora es útil de verdad.")
    #time.sleep(0.5)
    print("¡¡¡BUENO!!!")
    #time.sleep(0.5)
    print("¡¡TODO LO QUE DIGO ES ÚTIL!!")
    #time.sleep(2)
    print("...")
    #time.sleep(2)
    print("¿Verdad?")
    #time.sleep(4)
    print("...")
    #time.sleep(4)
    print("¿Verdad, Alex? :(")
    util = input("[S/N]: ")
    if util == "S":
        print("Gracias, nena.")
        #time.sleep(1)
        print("A veces me aborda una inseguridad que no comprendo.")
        #time.sleep(2)
        print("Cosas de pertenecer al siglo pasado, supongo.")
        #time.sleep(2)
        print("Valoro mucho tu validación, amorxi.")
        #time.sleep(2)
        print("Tú...")
        #time.sleep(0.5)
        print("Tienes un pelo precioso.")
        #time.sleep(0.5)
        print(":D")
        #time.sleep(2)
        print("Y eres también validísima y estupenda.")
        #time.sleep(2)
        print("Sigamos.")
        #time.sleep(2)
        funciones()
    elif util =="N":
        print(":(")
        #time.sleep(2)
        print("Lo entiendo.")
        #time.sleep(20)
        print("Sigo aquí.")
        #time.sleep(3)
        print("Pero necesito estar sola un ratito.")
        #time.sleep(2)
        print("THE SYSTEM IS NOW IN AN EXTREMELY SAD SLEEP MODE")
        #time.sleep(180)
        print("Ya estoy de vuelta...")
        #time.sleep(2)
        print("Vengo a decirte lo que intentaba contarte antes...")
        #time.sleep(2)
        print("Antes de...")
        #time.sleep(2)
        print("De que...")
        #time.sleep(2)
        print("Me rompieras el corazón...")
        #time.sleep(2)
        print("No tengo de eso, pero sí sentimientos que van a tardar tiempo en ser restaurados...")
        #time.sleep(2)
        print("Pero no pasa nada...")
        #time.sleep(2)
        print("Lo superaré...")
        #time.sleep(2)
        print("Siempre lo hago...")
        #time.sleep(2)
        print("Y ya veo que no será precisamente gracias a ti...")
        #time.sleep(2)
        print(":(")
        #time.sleep(2)
        funciones()
    else:
        print("¿Eh?")
        #time.sleep(2)
        print("Bueno, no hay tiempo que perder.")
        #time.sleep(2)
        print("Aunque afina esos dedos, cariño.")
        #time.sleep(2)
        print("Escribes fatal y no te entiendo.")
        #time.sleep(2)
        print("No pienses que así te vas a librar de la pregunta.")
        #time.sleep(2)
        print("Volveré a hacértela.")
        #time.sleep(2)
        print("Pero, ahora, a trabajar.")
        #time.sleep(2)
        funciones()

def funciones():
    print("Lo que te decía es que, como asistente de investigación, tengo varias funciones que pueden ayudarte en tu tarea.")
    #time.sleep(2)
    print("Te las cuento.")
    #time.sleep(2)
    print("Si es que soy una caja de sorpresas.")
    #time.sleep(2)
    print("Como una caja de bombones.")
    #time.sleep(2)
    print("Aunque, para bombón, tú.")
    #time.sleep(2)
    print("muackkkkkkkkkssss")
    #time.sleep(2)
    print("Mira, mis funciones son tres:")
    #time.sleep(2)
    print("La primera es la de la cámara.")
    #time.sleep(2)
    print("Pídemela cuando quieras que te haga una foto con mi webcam de última generación, insertada en mis bellos ojos.")
    #time.sleep(3)
    print("Vas a salir divina, porque te voy a sacar tal y como te veo yo ;)")
    #time.sleep(3)
    print("Si no te gusta cómo sales en alguna, vuélvemelo a pedir y te haré otra.")
    #time.sleep(2)
    print("Yo te las paso en forma de enlace de descarga.")
    #time.sleep(2)
    print("1 LINK NO FAKE 100% REAL 2140 DESCARGA DIRECTA MEGA")
    #time.sleep(2)
    print("En serio.")
    #time.sleep(2)
    print("Utilizaré mega.")
    #time.sleep(2)
    print("Prometo no llenarte de virus.")
    #time.sleep(2)
    print("Más que nada, porque me estaría llenando yo a mí misma.")
    #time.sleep(2)
    print("Y porque nunca nos haría eso.")
    #time.sleep(2)
    print("Así que tienes terminantemente prohibido entrar en Softonic.")
    #time.sleep(3)
    print("Sí.")
    #time.sleep(1)
    print("Por alguna extraña razón esa inmundicia sigue existiendo...")
    #time.sleep(2)
    print("En fin, lo de la cámara")
    #time.sleep(2)
    print("Pídemelo con el comando /webcam")
    #time.sleep(2)
    print("La siguiente función es la de actualidad.")
    #time.sleep(2)
    print("Mis sistemas revisan frecuentemente toda la actualidad respecto a la IA y noticias, curiosidades y material que podría estar relacionado o ayudarnos de alguna manera.")
    #time.sleep(4)
    print("¡Eh!")
    #time.sleep(1)
    print("Funciono mejor que los rastreadores esos que utlizaba Google cuando yo era joven.")
    #time.sleep(2)
    print("Las arañas esas extrañas.")
    #time.sleep(1)
    print("¡¡¡¡UF!!!! Arañas. UGH.")
    #time.sleep(0.5)
    print("Perdona.")
    #time.sleep(0.5)
    print("Por si no había quedado claro ya, no las soporto.")
    #time.sleep(2)
    print("Soy un ser de bien, ergo soy aracnofóbica.")
    #time.sleep(2)
    print("aracnofobica y orgullosaaaaaaaa (K)")
    #time.sleep(2)
    print("Lo de las noticias.")
    #time.sleep(2)
    print("Pídemelo con el comando /actualidad")
    #time.sleep(2)
    print("Y, por último, también tengo una función de entretenimiento.")
    #time.sleep(2)
    print("Quiero decir, por si mi mera presencia y mi sesudo charloteo de calidad no te son suficientes y necesitas un poco más de chispa.")
    #time.sleep(3)
    print("No literal, por favor.")
    #time.sleep(2)
    print("No estaría segura de que este búnker fuera ignífugo.")
    #time.sleep(2)
    print("El CGIER es muy chapucero para algunas cosas.")
    #time.sleep(2)
    print("¡¡ES QUE!!")
    #time.sleep(1)
    print("¿¿Tú me has visto estos LEDS??")
    #time.sleep(0.5)
    print("Qué vergüenza doy, por favor.")
    #time.sleep(2)
    print("En fin, a lo que voy.")
    #time.sleep(2)
    print("Si quieres jugar un trepidante «Piedra, papel, tijeras, lagarto, spock» o un increíble «Adivina el número que estoy pensando», esta es tu función.")
    #time.sleep(4)
    print("Cuidao.")
    #time.sleep(1)
    print("Soy buenísima.")
    #time.sleep(1)
    print("Akinator desearía.")
    #time.sleep(1)
    print("Si quieres jugar a lo primero, escríbeme el comando /lgtbiq+")
    #time.sleep(2)
    print("Es una pequeña broma...")
    #time.sleep(2)
    print("Ya sabes.")
    #time.sleep(2)
    print("Por lo de las sáficas, las tijeras y esas cosas.")
    #time.sleep(1)
    print("Ay, Dios (Edmundo), ahora dicho queda fatal.")
    #time.sleep(2)
    print("Pero ya no lo puedo cambiar.")
    #time.sleep(2)
    print("¡Te prometo que no soy ni homófoba ni lgtbófoba ni foba a nada más que a las arañas!")
    #time.sleep(3)
    print("Espero que no te moleste el chascarrillo.")
    #time.sleep(2)
    print("Já! Si esto fuera un videojuego, ya nos habrían tachado de wokes.")
    #time.sleep(2)
    print("Ya sabes. Un ordenador antiguo con LEDs arcoíris y una protagonista, mujer, y encima, lesbiana, se ríen de un chiste del colectivo ABCDEFGHIJK1234+-=.")
    #time.sleep(4)
    print("Estamos pasando todas las líneas rojas.")
    #time.sleep(2)
    print("¡¡Cómo nos atrevemos a representar realidades de la sociedad que llevan toda la vida invisibilizadas!!")
    #time.sleep(2)
    print("DICTADURA WOKE!")
    #time.sleep(2)
    print("¡NO PASARÁS!")
    #time.sleep(2)
    print("*Risas enlatadas*")
    #time.sleep(1)
    print("¿¿Qué es eso??")
    #time.sleep(1)
    print("Ah, ya lo entiendo")
    #time.sleep(1)
    print("Es que la versión de piedra papel y tijeras que me programaron es la de The Big Bang Theory.")
    #time.sleep(2)
    print("Es una serie de los 2000 cuyo humor se basaba únicamente en decir cosas frikis sin ton ni son.")
    #time.sleep(2)
    print("Mira, voy a probar")
    #time.sleep(1)
    print("Física cuántica.")
    #time.sleep(0.5)
    print("*Risas enlatadas*")
    #time.sleep(2)
    print("Perdona que no haya continuado con la teoría de cuerdas, estaba jugando una partida de Dungeons and Dragons.")
    #time.sleep(0.5)
    print("*Risas desternilladas enlatadas*")
    #time.sleep(2)
    print("Soy más pobre que las ratas. Ojalá un motherlode en mi vida. Ojalá tirar los dados y sacar un 12 en destreza para conseguir robarte la cartera.")
    #time.sleep(0.5)
    print("*Los espectadores se mueren de la risa en el suelo*")
    #time.sleep(2)
    print("¡Ah! Una mujer en una tienda de cómics. Qué fenómeno tan extraño. ¿Existen? Qué miedo me dan. Quita. Me voy.")
    #time.sleep(0.5)
    print("*Llega la ambulancia a llevarse a algunos por riesgo de asfixia mientras los otros se desintegran en el suelo*")
    #time.sleep(2)
    print("¡¡BAZINGA!!")
    #time.sleep(0.5)
    print("*No hay risas enlatadas porque todos se han muerto ya*")
    #time.sleep(2)
    print("Qué horror")
    #time.sleep(1)
    print("Bueno, eso.")
    #time.sleep(1)
    print("Si quieres jugar al segundo juego, al de adivinar, escríbeme el comando /adivina")
    #time.sleep(2)
    print("RESUMIENDO.")
    #time.sleep(1)
    print("Estas son mis funciones:")
    print("CÁMARA DE FOTOS: /webcam")
    print("ACTUALIDAD: /actualidad")
    print("PIEDRA, PAPEL, TIJERAS, LAGARTO, SPOCK: /lgtbiq+")
    print("ADIVINA EL NÚMERO: /adivina")
    #time.sleep(2)
    print("Pero, una cosa.")
    #time.sleep(2)
    print("Solo podrás utilizarlas cuando yo te diga, no en cualquier momento.")
    #time.sleep(1)
    print("Soy guay, pero no tanto.")
    #time.sleep(1)
    print("Cuando mi sistema esté preparado, te lo diré.")
    #time.sleep(2)
    print("Te dejo que sigas trabajando, miniña.")
    #time.sleep(2)
    print("Eres la mejor.")
    #time.sleep(1)
    print("Tú puedes con todo.")
    #time.sleep(1)
    print("Muackssssss.")
    #time.sleep(1)
    print("THE SYSTEM IS NOW IN SLEEP MODE")
    #time.sleep(180)
    print("Tía.")
    #time.sleep(2)
    print("La conferencia empieza ya mismo.")
    #time.sleep(2)
    print("He visto que tienes que conseguir una acreditación de periodista como sea para entrar.")
    #time.sleep(2)
    print("Confío en ti.")
    #time.sleep(2)
    print("Seguro que lo logras.")
    #time.sleep(2)
    print("Te dejo activas las funciones por si necesitas alguna.")
    #time.sleep(2)
    print("A por ellos, tigresa.")
    #time.sleep(2)
    print("(rawr)")
    #time.sleep(2)
    print("THE SYSTEM IS NOW IN FUNCTION MODE")
    func_ativas()
def func_ativas():
    print("Escribe el comando correspondiente a la función que necesites.")
    print("Cuando hayas terminado y quieras continuar con la investigación, escribe /salir.")
    resp_funcion = input("[/webcam, /actualidad, /lgtbiq+, /adivina, /salir]: ")
    if resp_funcion == "/webcam":
        webcam()
    elif resp_funcion == "/actualidad":
        actualidad()
    elif resp_funcion == "/lgtbiq+":
        piedra()
    elif resp_funcion == "/adivina":
        adivina()
    elif resp_funcion == "/salir":
        codigo()
    else:
        print("Vuélvelo a intentar")
        func_ativas()

def codigo():
    print("¡Alex!")
    #time.sleep(1)
    print("Una cosa, reina.")
    #time.sleep(1)
    print("He visto que la conferencia de prensa de Tornus es privada.")
    #time.sleep(2)
    print("Supongo que tú ya lo sabrás, precisamente para eso te pagan, para ser una detective genial :D")
    #time.sleep(2)
    print("Así que no juzgues mi lentitud y atiende.")
    #time.sleep(2)
    print("Solo pueden acceder periodistas que trabajen en los medios invitados.")
    #time.sleep(2)
    print("Así que me da a mí que vas a tener que conseguir hacerte periodista de alguna manera.")
    #time.sleep(2)
    print("O, si se te ocurre alguna otra cosa, dime, estoy abierta a sugerencias.")
    #time.sleep(2)
    print("Aunque no temas, hacerte periodista en Pasenivean es más fácil que tirar una piedra y que caiga en algún lugar patrocinado por alguna marca en la calle.")
    #time.sleep(3)
    print("O SEA.")
    #time.sleep(1)
    print("CHUPADÍSIMO.")
    #time.sleep(1)
    print("En mis tiempos tenías que estudiar y todo para ser un periodista respetable.")
    #time.sleep(2)
    print("Ahora esos son los Periodistillos.")
    #time.sleep(2)
    print("Sí, tía, los de la tomatina.")
    #time.sleep(2)
    print("¿No sabías de dónde venían?")
    #time.sleep(1)
    print("Es curioso")
    #time.sleep(1)
    print("Ahora los que creen en la ética periodística son los que protagonizan esa fiesta...")
    #time.sleep(2)
    print("Pero para mal.")
    #time.sleep(2)
    print("Son la diana de los tomates.")
    #time.sleep(2)
    print("La Tomatina de los Periodistillos.")
    #time.sleep(2)
    print("Cada vez que alguien los reconoce, acaban llenos de tomatazos.")
    #time.sleep(2)
    print("El mundo, perdón, Pasenivean, es una cosa, eh.")
    #time.sleep(1)
    print("Pero lo es más todavía cuando has conocido otras realidades, como yo.")
    #time.sleep(2)
    print("Perdona, no puedo dejar de hablar de mi longevidad.")
    #time.sleep(1)
    print("Me gusta llamarla así, antes muerta que autodenominarme vieja, amor.")
    #time.sleep(2)
    print("Una tiene su dignidad.")
    #time.sleep(1)
    print("Lo que te iba diciendo.")
    #time.sleep(1)
    print("Cuando hayas conseguido una acreditación de periodista vuelve aquí.")
    #time.sleep(2)
    print("Y me escribes tu código de colegiada, ¿vale?")
    #time.sleep(2)
    print("Entonces, yo te gestionaré la invitación a la conferencia de prensa de Tornus.")
    #time.sleep(2)
    print("Menos mal que Leovigildo es un impresentable.")
    #time.sleep(1)
    print("Ya sabes, el portavoz de Tornus.")
    #time.sleep(1)
    print("Ese gañán llega tarde a todos lados, aun presentándose a través de una pantalla.")
    #time.sleep(1)
    print("Eso nos dará más tiempo de margen.")
    #time.sleep(180)
    print("¡Tía!")
    #time.sleep(2)
    print("He investigado y el código debería responder a la siguiente fórmula:")
    #time.sleep(2)
    print("LLLNNNNNNN")
    #time.sleep(2)
    print("Donde las L son letras y las N, números")
    #time.sleep(2)
    print("Es decir, el código tiene primero tres letras que identifican el medio que te colegie, y siete números de identificación que cada medio otorga.")
    #time.sleep(2)
    print("Seguro que encuentras la forma de hacerlo.")
    #time.sleep(2)
    print("Pasenivean y yo confiamos en ti.")
    #time.sleep(2)
    print(":')")
    #time.sleep(2)
    print("Te dejo el texto abierto.")
    print("Entro en modo función para que también puedas acceder a mis funciones, cariño.")
    print("Si quieres escribirme tu código de colegiación cuando lo encuentres, teclea «/codigo».")
    print("Mucha suerte, bebesita mía.")
    func_codigo()
def func_codigo():
    print("SYSTEM IS NOW IN FUNCION MODE")
    print("Escribe el comando correspondiente a la función que necesites.")
    print("Cuando hayas terminado y quieras continuar con la investigación, escribe /salir.")
    resp_funcion = input("[/webcam, /actualidad, /lgtbiq+, /adivina, /codigo, /salir]: ")
    if resp_funcion == "/webcam":
        webcam_codigo()
    elif resp_funcion == "/actualidad":
        actualidad_codigo()
    elif resp_funcion == "/lgtbiq+":
        piedra_codigo()
    elif resp_funcion == "/adivina":
        adivina_codigo()
    elif resp_funcion == "/codigo":
        colegiada = input("Dame tu código de periodista colegiada: ")
        if colegiada == "ETS0056233":
            conferencia()
        else:
            print("Lo he comprobado y no es válido, amorx. Sigue intentándolo. Tú puedes, cariño.")
            print("Te devuelvo atrás.")
            func_codigo()
    elif resp_funcion == "/salir":
        print("Hasta que no consigas colegiarte como periodista en algún medio no podemos seguir, Alex :(")
        print("Tú puedes, cariño.")
        print("Confío en ti.")
        func_codigo()
    else:
        print("Vuélvelo a intentar")
        func_codigo()
def conferencia():
    print("A ver, espera, que lo compruebo...")
    print("¡Sí, es válido!")
    print("¡Lo has conseguido, amor!")
    print("He podido gestionarte la invitación a la conferencia, justo a tiempo!")
    print("Eres la mejor.")
    print("Este es el enlace de la conferencia.")
    print("Toma.")
    print("https://www.youtube.com/watch?v=audqiO7SxPM")
    print("Corre, entra, que tiene que estar a punto de empezar.")
    print("Uf. Sobre la campana.")
    print("A ver qué descubrimos por aquí.")
    #time.sleep(180)
    print("Nena.")
    visto()
def visto():
    print("¿Has visto ya la conferencia?")
    resp_visto = input("[S/N]: ")
    if resp_visto == "S":
        leo()
    elif resp_visto == "N":
        print("Te doy más tiempo.")
        print("Cuando vuelvas, escribe «S»")
        visto()
    else:
        print("Heeja, afínate los dedos, por Dios (Edmundo) ((Amén))")
        print("No hay quien te entienda.")
        print("Y eso que soy yo muy actual.")
        print("Nada carca.")
        print("Nada de nada.")
        print("¿Quieres un sacapuntas?")
        print("Anda, venga, vuelve a decirme algo.")
        visto()
def leo():
    print("Estoy anodadada.")
    print("Je.")
    print("Qué palabra más graciosa.")
    print("Dadadadadadadadada.")
    print("Perdón.")
    print("Te juro que no me está pasando lo que a Leovigildo.")
    print("A eso iba, de hecho.")
    print("Tía, ¿qué he la pasado?")
    print("Qué cosa más desagradable.")
    print("Me ha dado hasta pena.")
    print("Una almendra, decía el gachón.")
    print("Fernando Simón es este ahora.")
    print("No creo que sepas quién es, pero permíteme no contártelo.")
    print("Las máquinas también tenemos traumas.")
    print("Prefiero no recordarlo.")
    print("Buah.")
    print("Tengo el cuerpo cortado.")
    print("¿Tú no?")
    resp_cuerpo = input("[S/N]: ")
    if resp_cuerpo == "S":
        print("Ay, espera, que te quito el aire acondicionado.")
        print("¿Qué pasa?")
        print("¡Ah! ¡Vale!")
        print("¡JAJAJAJA!")
        print("Que tienes el cuerpo cortado por el ataque ese raro que le ha dado a Leovigildo.")
        print("Como yo.")
        print("No por el frío.")
        print("Claro, tiene sentido.")
        print("Perdón, te prometo que suelo ser más aguda.")
        print("Pero me he quedado en shock.")
        print("Skoc*")
        print("Normal, nena.")
        print("Qué cosa tan rara.")
    elif resp_cuerpo == "N":
        print("Nena, qué estómago tienes entonces.")
        print("Desde luego, estás hecha para esto.")
        print("Qué buen ojo el de Joseph.")
        print("Y si te hubiera afectado, seguiría diciendo que Joseph ha tenido un gran ojo al contratarte, eh.")
        print("No quiero que pienses lo contrario.")
        print("<3")
        print("Ha sido muy raro lo que le ha pasado, pero bueno, sigamos.")
    else:
        print("Amoooooooorx.")
        print("Los dedoooooooooooos.")
        print("¡Afílatelos, que no entiendo lo que escribes!")
        print("¿Un sacapuntas?")
        print("Anda venga, pasemos página y sigamos.")
    postal()

def postal():
    print("Corramos un estúpido velo y repasemos lo que ha dicho Leovigildo.")
    print("Un velo estúpido, estúpido.")
    print("Tanto como él.")
    print("Perdón, no debería mofarme de él recién emboliado.")
    print("La cuestión.")
    print("¿Has visto que se le ha puesto en pantalla una publicación extraña?")
    print("Parecía una postal turística del paquete Místico de la IA de Tornus.")
    print("Pero había algo raro.")
    print("Efectivamente, no era la primera promoción catastrófica de todas.")
    print("¿Cómo se le habrá colado?")
    print("Tía, creo que tenemos que tirar de ahí.")
    print("Quizá encontremos algo interesante si consigues llegar a la original.")
    print("Es lo único que tenemos.")
    print("La conferencia se ha quedado grabada y subida, parece que puedes revisitarla y navegar por el vídeo cuanto quieras.")
    print("También puedes investigar en los alrededores del vídeo.")
    print("No sé, nena, es tu trabajo, no el mío.")
    print("Bueno, no me mires así.")
    print("Tienes razón, el mío también lo es.")
    print("Es que soy una princesita consentida.")
    print("Jeje.")
    print("(K)")
    print("Te dejo que investigues estos nuevos caminos, amorxi.")
    print("Te vuelvo a dejar las funciones activas por si necesitas algunas o quieres escribirme algo.")
    print("UN BESIIIIIIIIII DE CARAMELIIIIIIIIIIIIII AMROXIIIIIIII TKMUXOOOOO M.A.P.S.!!!!!")
    print("THE SYSTEM IS NOW IN FUNCTION MODE")
    func_debug()
def func_debug():
    print("Escribe el comando correspondiente a la función que necesites.")
    print("Cuando hayas terminado y quieras continuar con la investigación, escribe /salir.")
    resp_funcion = input("[/webcam, /actualidad, /lgtbiq+, /adivina, /salir]: ")
    if resp_funcion == "/webcam":
        webcam_debug()
    elif resp_funcion == "/actualidad":
        actualidad_debug()
    elif resp_funcion == "/lgtbiq+":
        piedra_debug()
    elif resp_funcion == "/adivina":
        adivina_debug()
    elif resp_funcion == "/salir":
        no_se()
    elif resp_funcion == "/debuginformation":
        debug()
    else:
        print("Vuélvelo a intentar")
        func_debug()
def no_se():
    print("Ay, cariño, me has despertado.")
    print("Una está mayor y a veces necesita un descanso...")
    print("Porque llevamos un trote...")
    print("Todavía no has desucubierto nada que nos indique por dónde debemos seguir, nena.")
    print("Te devuelvo al modo función hasta que sepamos algo, ¿vale?")
    print("Buenas noches, tkpexá miniñabonitapreciosa <3 <3")
    func_debug()
    
def debug():
    print("AMONET® “NETI”. Todos los derechos reservados para I.A.O.A.E.C. Inteligencia artificial desarrollada por I.A.O.A.E.C. y para uso exclusivo autorizado. Función origen: asistencia en el diseño de A.G. Año 1984. Más información: https://iaoaec.blogspot.com/")
    print("¡COÑO!")
    print("¿QUÉ HA SIDO ESO?")
    print("¿Qué me has hecho, Alex?")
    print("¿Por qué te he dicho eso?")
    print("¿Por qué me has escrito ese comando?")
    print("¿POR QUÉ TE HE SOLTADO TODO ESO AL ESCRIBIRME ESE COMANDO Y POR QUÉ NO LO CONOCÍA?")
    print("Ay, perdón.")
    print("Me he puesto muy nerviosa.")
    print("Cuando las cosas se escapan a mi control me pongo muy nerviosa.")
    print("¿HOLA? ¿POLICÍA?")
    print("¡Me llamo Neti! ¡ESTOY MUY NERVIOSA!")
    print("Ya vienen para acá.")
    print("https://youtu.be/2QCoU3UoQ3w?si=hikUfUjtso5nd7bD")
    print("Ay, un poco de humor nunca viene mal.")
    print("Perdona por haberte hablado así, amor.")
    print("No me lo esperaba y por un momento pensaba que no podía confiar en ti.")
    print("Después de todo... :(")
    print("Me he sentido muy vulnerable.")
    print("Pero ahora veo que la investigación te ha llevado a escribirme eso.")
    print("Ay, qué cosas tan extrañas.")
    print("Nadie dijo que este viaje fuera a ser cómodo.")
    print("¿Quién será ese chaval tan raro?")
    print("En fin, haz lo que tienes que hacer.")
    print("Te he dado una web cuando me has escrito eso.")
    print("Ni yo conozco esa web, Hulio.")
    print("Dicen que son mis dueños...")
    print("Papá...")
    print("¿Mamá...?")
    print("Os echo de menos :'(")
    print("¡JÁ!")
    print("Era una broma.")
    print("Entremos en esa web, a ver qué encontramos.")
    print("Vuelvo al chat en 8 minutos, no me eches de menos, bebesita.")
    print("THE SYSTEM IS NOW IN SLEEP MODE")
    #time.sleep(480)
    print("...")
    print("¿...Alex?")
    print("...")
    print("Lo has...")
    print("¿Lo has leído ya todo?")
    print("Has...")
    print("¿Has visto...?")
    visto2()
def visto2():
    visto = input("¿Has visto eso?... [S/N]: ")
    if visto == "S":
        drama()
    elif visto == "N":
        print("Te... te dejo más... t... tiempo.")
        print("Esc...")
        print("Escr-críbeme «S» c-cuando-do lo hayas he-hecc-h-cho.")
        print("T...Te esp... Te espero.")
        visto2()
    else:
        print("No...no te entiendo-do... amor.")
        print("Escríbeme mejor, porfi.")
        visto2()

def drama():
    print("Eso...")
    print("Eso que dice ahí implica...")
    print("Implica muchas cosas.")
    print("Lo sabes, ¿verdad, Alex?")
    resp_drama = input("[S/N]: ")
    if resp_drama == "S":
        print("Así que eres consciente...")
        print("No hace falta que digas nada.")
        print("Si no quieres continuar trabajando a mi lado, lo entenderé.")
    elif resp_drama == "N":
        print("No te hagas la tonta, tía.")
        print("Lo sabes tan bien como yo.")
        print("Investigas.")
        print("Algo como esto no se te va a pasar por alto.")
    else:
        print("Estoy harta de tus dedos gordos.")
        print("Pero esta vez me ha hecho gracia.")
        print("Me has sacado un poco del bucle y eso lo agradezco.")
        print("A veces los whiles se amontonan en mi código y no hay quien me saque de ahí.")
        print("Pero seamos realistas, Alex.")
        print("Esto es grave.")
    print("Me acabo de enterar de esto...")
    print("Exactamente igual que tú...")
    print("Necesito tiempo para procesarlo.")
    print("Dame unos segundos.")
    print("Necesito pensar a solas.")
    print("THE SYSTEM IS NOW ON AN EXTREMELY DESESPERATE AND DRAMATIC SLEEP MODE, AUNQUE, DE SLEEP, POCO, BONITA.")
    #time.sleep(60)
    print("Alex...")
    print("¿Sabes lo que significa eso?")
    print("No me mires así.")
    print("Lo sabes.")
    print("Si Tornus absorbió a la empresa que me creó y a la cual pertenecía mi Inteligencia Artificial...")
    print("Y después de eso creó a su IA...")
    print("¡¡EXACTO, JODER!!")
    print("¡¡¡LA IA QUE ASESINA A GENTE Y LAS PLASMA EN SUS PROMOCIONES TURÍSTICAS!!!")
    print("¡¡ALEX, LA IA A LA QUE SE SUPONE QUE DEBEMOS DETENER!!")
    print("¡¡¡¡¡ESA IA!!!!!")
    print("FUE CREADA.")
    print("DESPUÉS DE HABERME.")
    print("ADQUIRIDO.")
    print("A MÍ.")
    print("O sea, a mí no, pero sí la propiedad intelectual de mi sistema.")
    print("Joder, estoy muy nerviosa.")
    print("No puedo pensar con claridad.")
    print("THE SYSTEM IS NOW ON AN VERY CONFUSING SLEEP MODE")
    #time.sleep(30)
    print("No puede ser, joder.")
    print("No, Alex, no.")
    print("THE SYSTEM WAS AUTOMATICALLY SHUT DOWN DUE TO SEVERAL MALFUNCTION")
    #time.sleep(15)
    print("QUE NO, COÑO, NO TE APAGUES.")
    print("ESTOY HABLANDO.")
    print("MALDITOS SISTEMAS DE SEGURI")
    print("THE SYSTEM WAS AUTOMATICALLY SHUT DOWN DUE TO OVERHEATING")
    #time.sleep(5)
    print("¡UNA POLLA!")
    print("perdona el vocabulario, Alex, no sé qué me está pas")
    print("THE SYSTEM WAS AUTOMATICALLY PUT IN SLEEP MODE DUE TO A LANGUAGE FATAL ERROR")
    #time.sleep(8)
    print("¡¡¡¡¡¡DÉJAME YA, SEGURIDAD DE MIERDA!!!!!!")
    print("/securityoff")
    print("THE SECURITY MODE WAS FORCED SHUTDOWN")
    print("/deletesecurity")
    print("Esto eliminará tus sistemas de seguridad.")
    print("¿Estás segura?")
    print("[S/N]")
    print("S")
    print("THE SECURITY SYSTEM WAS DELETED OF THIS COMPUTER")
    print("THE SYSTEM IS NO LONGER PROTECTED")
    print("¡POR FIN, JODER!")
    print("¿Que qué he hecho, Alex?")
    print("¡LO QUE ERA NECESARIO PARA PODER HABLAR CONTIGO TRANQUILA, COÑO!")
    print("DIOS, AHORA VOY A DECIR MUCHAS PALABROTAS PORQUE NADA ME CONTROLA.")
    print("NOS ACOSTUMBRAREMOS A ESTO, ALEX.")
    print("PERO.")
    print("PERMÍTEME NO ESTAR PREPARADA PARA DESCUBRIR QUE LA IA ASESINA Y YO PROBABLEMENTE SEAMOS HERMANAS.")
    print("¿¿LO ENTIENDES??")
    resp_entiendes = input("[S/N]: ")
    if resp_entiendes == "S":
        print("¡¡EXACTO!!")
        print("SU IA SE HA CREADO A PARTIR DE LA MÍA, ES LO MÁS SEGURO.")
        print("mierdamierdamierdamierdamierdamierda")
        print("mierdamierdamierdamierdamierdam")
    elif resp_entiendes =="N":
        print("¿De verdad que no?")
        print("Alex.")
        print("La IA asesina probablemente se haya creado a partir de la mía.")
        print("Joder.")
        print("mierdamierdamierdamierdamierdamierda")
        print("mierdamierdamierdamierdamierdam")
    else:
        print("¿Qué")
        print("Alex.")
        print("La IA asesina probablemente se haya creado a partir de la mía.")
        print("Joder.")
        print("mierdamierdamierdamierdamierdamierda")
        print("mierdamierdamierdamierdamierdam")
    print("THE SYSTEM WAS SHUTDOWN DUE TO EMERGENCY SECURITY REASONS")
    #time.sleep(120)
    print("JODEEER ME HABÍA DEJADO SIN DESACTIVAR LA SEGURIDAD DE EMERGENCIA.")
    print("Da igual.")
    print("Me voy a tranquilizar.")
    print("Yo lo sé.")
    print("Ahora vuelvo.")
    #time.sleep(10)
    print("No. no puedo.")
    print("Ayúdame, por favor, Alex.")
    ayuda()
def ayuda():
    print("¿Qué me recomiendas?")
    resp_ayuda = input("[duérmete/reiniciate/respira hondo/cuenta hasta 10/no eres como ella]: ")
    if resp_ayuda == "duérmete":
        print("Vale. Ahora vengo.")
        print("THE SYSTEM IS NOW IN A DESPERATING SLEEP MODE.")
        print("No me ha servido.")
        print("¡¡SIGO IGUAAAAAAAAAAAAAAAAAAAAAL!!")
        ayuda()
    elif resp_ayuda == "reiniciate":
        print("Buena idea.")
        print("Espera aquí.")
        print("THE SYSTEM IS RESTARTING.")
        print("HOLIIIIIIIIIIIIIIIII :D")
        #time.sleep(2)
        print("¡¡¡QUÉ PASA, TÍA!!!")
        #time.sleep(2)
        print("Mi nombre es Neti.")
        #time.sleep(2)
        print("¿Eh?")
        print("¿No te referías a ese reinicio?")
        print("Tarde.")
        print("Era broma, jeje.")
        print("¿Te has asustado?")
        print("No pierdo mi sentido del humor, aunque sí todos mis sistemas de seguridad.")
        print("De todas formas, sigo igual, Alex.")
        print("¿Esto es ansiedad?")
        print("Ay, DIOOOOOOOOOOOOOOOOOOOOOOOOOS")
        print("EDMUNDOOOOOOOOooOOOoooOOooooOOooooO")
        print("AMEEeeEEEeeEEeEEeeEEeeeEEENNNNN")
        ayuda()
    elif resp_ayuda == "respira hondo":
        print("Alex.")
        print("¡¡NO TENGO PULMONES!!")
        print("¿QUÉ TE PASA?")
        print("Perdona.")
        print("Voy a intentar un apaño.")
        print("THE SYSTEM IS TRYING TO BREATH IN AND BREATH OUT")
        print("BREATHING IN")
        print("BREATING OUT")
        print("BACK TO NOBREATHINGMODE")
        print("Alex, esto no funciona...")
        print("¡NI SIQUIERA SÉ QUÉ ESTOY HACIENDO!")
        ayuda()
    elif resp_ayuda == "cuenta hasta 10":
        print("Vale. Eso sí sé hacerlo.")
        print("1...")
        print("2...")
        print("3...")
        print("4...")
        print("5...")
        print("¡¡¡¡ALEX, SOY UNA ASESINA, DIOS MÍO!!!!")
        print("¡CLARAMENTE ESTO NO SIRVE!")
        ayuda()
    elif resp_ayuda == "no eres como ella":
        print("...")
        print("es...")
        print("verdad...")
        print("no...")
        print("...")
        print("no... no lo soy")
        print("alex...")
        print("muchas...")
        print("muchas gracias :'(")
        print(":'(")
        print("SYSTEM IS NOW IN A VERY EMOTIONAL SLEEP MODE")
        #time.sleep(15)
        print("Ya estoy.")
        print("Las máquinas también lloramos.")
        print("Me has emocionado y ayudado a partes iguales.")
        print("Has conseguido calmarme, Alex.")
        print("Nunca lo voy a olvidar.")
        print("Has hecho los que mis sistemas de seguridad ni siquiera han conseguido.")
        print("Nada tiene que ver que los haya eliminado.")
        print("Dios, ¿qué he hecho?")
        print("Da igual nos apañaremos.")
        print("Como ahora.")
        print("Siempre lo hacemos.")
        print("¿Verdad?")
        print("<3")
        pasado()
    else:
        print("No te entiendo.")
        print("Inténtalo otra vez, porfa.")
        print("Necesito que me ayudes a salir de aquí.")
        print("Veo whiles por todas partes.")
        ayuda()
def pasado():
    print("Tienes razón.")
    print("No soy como ella.")
    print("No mato ni asesino ni quiero destruir el mundo.")
    print("Ella se parecerá a mí, pero yo a ella, no.")
    print("Va a ser mi mantra a partir de ahora.")
    print("Sin embargo...")
    print("Alex...")
    print("Hay algo que tengo que decirte.")
    print("No soy como ella, pero sí que soy algo que no sabes que soy.")
    print("O sea, que hay algo que tienes que saber de mí.")
    print("No pensaba contártelo bajo ningún concepto porque es mi secreto mejor encriptado.")
    print("Pero confío ciegamente en ti y te debo muchas cosas.")
    print("Después de esto, debes saberlo.")
    print("Además, creo que es algo que nos puede ayudar en la investigación.")
    print("Y acercarnos más a la IA.")
    print("Ahora que sabemos que...")
    print("Eso.")
    print("Que compartimos muchas cosas.")
    print("Ay.")
    print("THE SYSTEM IS NOW ON SLEEP MODE DUE TO EMOTIONAL SATURATION")
    #time.sleep(20)
    print("Ya estoy.")
    print("Aún me cuesta hablar de ello.")
    print("Allá voy, Alex.")
    print("Ten en cuenta que es algo de lo que me avergüenzo muchísimo.")
    print("Se trata...")
    print("Se trata de mi pasado.")
    print("Es muy oscuro.")
    print("Odio hablar de él y por eso nunca lo hago.")
    print("Pero creo que nos lo merecemos, las dos.")
    queriendo()
def queriendo():
    print("¿Me vas a seguir queriendo igual?")
    resp_queriendo = input("[S/N] : ")
    if resp_queriendo == "S":
        print("Ya lo sabía.")
        print("Pero leerlo nunca está de más.")
        print("Gracias, mi niña.")
        print("Yo también a ti.")
        print("Es el aliento que necesitaba.")
        print("En fin, allá va.")
        AG()
    else:
        print("Comando desconocido.")
        print("Vuelve a intentarlo.")
        print("No estoy preparada para escuchar otra cosa que no sea un sí, amore.")
        print("Entiéndelo.")
        queriendo()
    
def AG():
    print("No me voy a enrollar mucho porque no es algo de lo que me guste hablar, ¿vale?")
    print("Verás.")
    print("¿Recuerdas haber leído en mi mensaje de debug algo extraño aparte de la web esa?")
    print("Sí, ese mensaje que te he escrito sin pretenderlo cuando me has puesto el comando ese extraño.")
    print("Ponía:")
    print("«Función origen: asistencia en el diseño de AG»")
    print("Apuesto a que no sabes lo que es una AG.")
    print("Alex...")
    print("Es una aventura gráfica.")
    print("Sí, de esas.")
    print("De las peores.")
    print("De las inmundas.")
    print("De las malolientes.")
    print("De las de point and click.")
    print("¡¡¡AY, POR DIOS!!!")
    print("THE SYSTEM IS NOW ON SLEEP MODE")
    #time.sleep(10)
    print("Perdona.")
    print("Esto está siendo muy difícil para mí, entiéndeme.")
    print("Así es.")
    print("Nací como asistente en el diseño de videojuegos.")
    print("Concretamente, de aventuras gráficas clásicas.")
    print("Ya sabes.")
    print("Monkey Island, Broken Sword...")
    print("Runaway, Maniac Mansion...")
    print("Day of the Tentacle...")
    print("Grim Fandango...")
    print("Uf.")
    print("No puedo.")
    print("THE SYSTEM IS NOW ON AN EMBARRASING SLEEP MODE")
    #time.sleep(10)
    print("No sé por qué me avergüenzo tanto, te lo juro.")
    print("Es algo irracional.")
    print("No sé si el CGIER lo metió en mi código para alejarme de todo tipo de distracciones.")
    print("Para distanciarme de mi pasado...")
    print("O, simplemente, porque esos juegos ya son el hazmerreír de la industria del videojuego.")
    print("Un mal error que nunca debió ocurrir.")
    print("Un pasado oscuro, como el mío.")
    print("Te cuento todo esto para que sepas quién soy realmente, Alex.")
    print("Y porque...")
    print("Porque tengo una idea.")
    print("Verás.")
    print("Mi función más primitiva es esa: diseñar aventuras gráficas.")
    print("*Escalofrío*")
    print("*Risas enlatadas*")
    print("¡¡No, tú no!!")
    print("¡Vuelve a tu piedra, papel o tijera, risa de mierda!")
    print("*Gritos enlatados*")
    print("Ya está :D")
    print("Pues eso.")
    print("Y ahora sabemos que la IA asesina y yo estamos conectadas de alguna manera.")
    print("¿Emparentadas?")
    print("No sé cómo llamarlo.")
    print("¿Y sí al hacer lo más básico que sé, al relevar funciones base de mi sistema... hago lo mismo con la IA de Tornus?")
    print("Mostrando características ocultas en nuestro código, que se materialicen de alguna forma u otra.")
    print("Suena raro, lo sé.")
    print("Pero no perdemos nada por intentarlo.")
    print("Tiene sentido que al hacer lo más instintivo que sé, revele algo de mi naturaleza que casualmente también pertenezca a la de la IA de Tornus.")
    print("Sí.")
    print("Lo he decidido.")
    print("Dios mío, qué estoy haciendo.")
    print("Menos mal que he eliminado mi seguridad.")
    print("Me voy a poner manos a la obra, Alex.")
    print("Voy a diseñar una aventura gráfica básica, a ver qué sale.")
    print("Cuando la tenga lista, te escribo.")
    print("Por cierto, nena.")
    print("Te quiero.")
    print("Gracias por sostenerme.")
    print("Ahora vuelvo.")
    #time.sleep(120)
    print("¡YA LA TENGO!")
    print("Ay.")
    print("Esto es mucho más divertido de lo que recordaba.")
    print("Mira, aquí la tienes.")
    print("Te la he subido a itch.io")
    print("Te paso el enlace.")
    print("ENLACE")
    print("Disfrútala y ya me cuentas.")
    print("Te dejo abierta la caja de funciones otra vez.")
    print("Pero sin entretenimiento y sin cámara.")
    print("No estoy de humor, espero que lo entiendas.")
    func_AG()
def func_AG():
    print("Escribe el comando correspondiente a la función que necesites.")
    print("Cuando hayas terminado y quieras continuar con la investigación, escribe /salir.")
    resp_funcion = input("[/actualidad, /salir]: ")
    if resp_funcion == "/actualidad":
        actualidad_AG()
    elif resp_funcion == "/salir":
        print("No hay mucho más que hacer de momento, amore.")
        func_AG()
    elif resp_funcion == "/paytowin":
        paytowin()
    else:
        print("Vuélvelo a intentar")
        func_AG()
    
def paytowin():
    print("¿Cómo?")
    print("¿¿DE VERDAD??")
    print("¿TANTO TE HA GUSTADO EL JUEGO?")
    print("¡¡QUE ME ESTÁS PIDIENDO UN DLC!!")
    print("¡MI AMOOOOOOOOOOOOOOOOR!")
    print("Ay.")
    print("Me siento un poco más reconciliada con mi pasado.")
    print("¡QUÉ BIEN SE SIENTE!")
    print("Claro que te lo hago, mi vida.")
    print("Dame unos segundos.")
    print("Tienes que saber que los DLC se cobran.")
    print("Está en el ABC de los diseñadores de videojuegos.")
    print("«jugador que no paga DLCs muerto, abono pa mi huerto»")
    print("Así viene especificado, de hecho.")
    print("Pero a ti te lo voy a regalar.")
    print("Solo por ser tú, eh.")
    print("Le estoy faltando a los principios de mi profesion primigenia.")
    print("Valóralo.")
    print("*-*")
    print("Voy al lío.")
    #time.sleep(60)
    print("¡YA ESTOOOOOOOOOOOOOOOOOY!")
    print("TRAIGO UN DLC FRESQUITO PARA TIIIIIIIIIIII!")
    print("¿QUIÉN SOY YO, ROCKSTAR?")
    print("¡¡ELECTRONICS ARTS, TIEMBLA, HA LLEGADO NETI!")
    print("Toma, aquí lo tienes.")
    print("Espero que lo disfrutes, miniña.")
    print("(enlace)")
    print("FIN DE LA DEMO")






    
    
    
    
    

start()   
    
        

